# Generated by Django 5.1.1 on 2024-10-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_examenes', '0002_pregunta_orden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultado',
            old_name='puntuaje',
            new_name='puntaje',
        ),
        migrations.AddField(
            model_name='resultado',
            name='respuestas',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
