# Generated by Django 5.1.1 on 2024-10-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_examenes', '0003_rename_puntuaje_resultado_puntaje_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultado',
            old_name='puntaje',
            new_name='puntuacion',
        ),
    ]
