# Generated by Django 5.1.1 on 2024-10-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_examenes', '0005_rename_randomizar_respuestas_examen_randomizar_opciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='orden',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='explicacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
