# Generated by Django 5.1.1 on 2024-10-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_examenes', '0006_remove_pregunta_orden_pregunta_explicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='explicacion',
        ),
    ]
