# Generated by Django 5.1.1 on 2024-10-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_examenes', '0007_remove_pregunta_explicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='explicacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
