# Generated by Django 5.1.1 on 2024-10-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_examenes', '0008_pregunta_explicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='dividir_por_temas',
        ),
        migrations.DeleteModel(
            name='Tema',
        ),
    ]
