# Generated by Django 5.1.2 on 2024-10-25 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_examenes",
            "0013_examen_alumnos_asignados_usuario_alumnos_asignados_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="examen",
            name="creado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
