# Generated by Django 5.1.2 on 2024-10-25 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_examenes", "0014_alter_examen_creado_por"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultado",
            name="alumno",
            field=models.ForeignKey(
                default=8,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultados",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="resultado",
            name="examen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultados",
                to="app_examenes.examen",
            ),
        ),
    ]
