# Generated by Django 5.1.2 on 2024-10-26 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_examenes", "0015_resultado_alumno_alter_resultado_examen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultado",
            name="alumno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
