# Generated by Django 5.1.2 on 2024-10-26 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_examenes", "0016_alter_resultado_alumno"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resultado",
            name="alumno",
        ),
        migrations.AddField(
            model_name="resultado",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultados",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
